name: Build and deploy

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [ 18.x ]

        steps:
            -   uses: actions/checkout@v3
            -   name: Use Node.js ${{ matrix.node-version }}
                uses: actions/setup-node@v3
                with:
                    node-version: ${{ matrix.node-version }}
                    cache: 'npm'
            -   run: npm ci
            -   run: npm run build --if-present
            -   run: npm test
#            -   uses: aws-actions/setup-sam@v2
#                with:
#                    use-installer: true
#            -   uses: aws-actions/configure-aws-credentials@v2
#                with:
#                    aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#                    aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#                    aws-region: eu-central-1
#            -   run: aws s3 sync ./build/* 's3://avcv.info'

